### ISSUE TITLE
Non-existent tt-system-tools URL being used by the tt-installer script

### ISSUE THREAD

**Issue by hshahTT** [tenstorrent/tt-installer#19]
The tt-installer script is attempting to download the Debian file for tt-system-tools v1.3.1 at the wrong URL, resulting in a 404 error:

![Image](https://github.com/user-attachments/assets/34c1bb38-aa1a-429a-9533-95abdef1f0c5)

Correct URL: https://github.com/tenstorrent/tt-system-tools/releases/download/v1.3.1/tenstorrent-tools_1.3.1_all.deb
URL it's trying to download: https://github.com/tenstorrent/tt-system-tools/releases/download/upstream/v1.3.1/tenstorrent-tools_1.3.1-1_all.deb

Steps to reproduce:
1. Create a fresh Cloud VM.
2. Run the tt-install script: `/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/tenstorrent/tt-installer/refs/heads/main/install.sh)"`

**Comment by knauth** [comment]
Fixed by PR #20, thanks for the flag!

**Comment by hshahTT** [comment]
Hi, @knauth this unfortunately didn't fix it because there's an extra "-1" in the URL that doesn't exist in the correct URL: 

![Image](https://github.com/user-attachments/assets/4673bb1d-0d78-4591-9fc5-aa4fdb9e5016)

I think you'll have to remove the "-1" from this line in the install.sh script as well: https://github.com/tenstorrent/tt-installer/blob/cdcbd609f8897f6fe276faaf23fa04c0afdf1957/install.sh#L587

Or add "-1" to the v1.3.1 package name here: https://github.com/tenstorrent/tt-system-tools/releases
