### ISSUE TITLE
404 Not Found - Time Out on fwbundle

### ISSUE THREAD

**Issue by einnesTT** [tenstorrent/tt-installer#34]
Today when running tt-installer, the step hangs on getting the `fwbundle` details: 

```
--2025-05-16 13:47:15--  https://github.com/tenstorrent/tt-firmware/releases/download/v18.3.0/fw_pack-18.3.0.0.fwbundle
Resolving github.com (github.com)... 140.82.113.3
Connecting to github.com (github.com)|140.82.113.3|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2025-05-16 13:47:15 ERROR 404: Not Found.
```

The script then exits without completing set up.

**Comment by warthog9** [comment]
Resolved in #33

**Comment by einnesTT** [comment]
This is not resolved, I just got the same result a few moments ago - 

```
--2025-05-16 18:34:04--  https://github.com/tenstorrent/tt-firmware/releases/download/v18.3.0/fw_pack-18.3.0.fwbundle
Resolving github.com (github.com)... 140.82.113.3
Connecting to github.com (github.com)|140.82.113.3|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2025-05-16 18:34:04 ERROR 404: Not Found.
```
